version: '3.8'

services:
  # ISP Simulation
  isp:
    image: nat-config
    container_name: isp
    hostname: isp
    command: ["sh", "-c", "/usr/local/bin/print_ips.sh && /usr/local/bin/routes.sh while true; do sleep 3600; done"]
    networks:
      - isp_net
      - public_net
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./services/isp/iptables.rules:/etc/iptables.rules:ro
      - ./services/isp/routes.sh:/usr/local/bin/routes.sh:ro
      - ./print_ips.sh:/usr/local/bin/print_ips.sh:ro
    entrypoint: ["sh", "-c", 'iptables-restore < /etc/iptables.rules && while :; do sleep 3600; done']
    ports:
      - "9091:80"
    tty: true
    stdin_open: true

  # Router Simulation
  router:
    image: nat-config
    container_name: router
    hostname: router
    entrypoint: ["sh", "-c", "iptables-restore < /etc/iptables.rules && /usr/local/bin/print_ips.sh && /usr/local/bin/routes.sh && while :; do sleep 3600; done"]
    networks:
      - isp_net
      - home_net
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./services/router/iptables.rules:/etc/iptables.rules:ro
      - ./print_ips.sh:/usr/local/bin/print_ips.sh:ro
      - ./services/router/routes.sh:/usr/local/bin/routes.sh:ro
    ports:
      - "9092:80"
    tty: true
    stdin_open: true
  # Device Simulations
  device1:
    image: nat-config
    container_name: device1
    hostname: device3
    command: ["sh", "-c", "/usr/local/bin/print_ips.sh && while true; do sleep 3600; done"]
    networks:
      - home_net
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    entrypoint: ["sh", "-c", "while true; do sleep 3600; done"]
    ports:
      - "9094:80"
    tty: true
    stdin_open: true

  # Public Node Simulation
  public_node:
    image: nat-config
    container_name: public_node
    hostname: public_node
    command: ["sh", "-c", "/usr/local/bin/print_ips.sh && /usr/local/bin/routes.sh && while true; do sleep 3600; done"]
    networks:
      - public_net
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./print_ips.sh:/usr/local/bin/print_ips.sh:ro
      - ./services/public_node/routes.sh:/usr/local/bin/routes.sh:ro
      - ./services/public_node/iptables.rules:/etc/iptables.rules:ro
    ports:
      - "9097:80"
    tty: true
    stdin_open: true

networks:
  isp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 203.0.113.0/24
  home_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  public_net:
    driver: bridge
    ipam:
      config:
        - subnet: 198.51.100.0/24
